### ISSUE TITLE
Problem with CVSS 3.1

### ISSUE THREAD

**Issue by AgoraSecurity** [mort666/cvss_rating#2]
Hello,

I'm using NVD latest feed and it includes CVSS 3.1 for some CVEs.

I get the following error:
```
/usr/local/rvm/gems/ruby@tools/gems/cvss_rating-0.6.0/lib/cvss_rating/cvss3_vectors.rb:76:in `cvss3=': Bad CVSS 3.0 Vector String (RuntimeError)
  from /usr/local/rvm/gems/ruby@tools/gems/cvss_rating-0.6.0/lib/cvss_rating/cvss3_vectors.rb:40:in `block in parse'
  from /usr/local/rvm/gems/ruby@tools/gems/cvss_rating-0.6.0/lib/cvss_rating/cvss3_vectors.rb:38:in `each'
  from /usr/local/rvm/gems/ruby@tools/gems/cvss_rating-0.6.0/lib/cvss_rating/cvss3_vectors.rb:38:in `parse'
...
```

My CVSS v3 string is:
`"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"`

I understand the problem is that it's 3.1 instead of 3.0

It would be nice to have support for 3.1 (only change required is to support 3.1 in the string)

Change must be done in https://github.com/mort666/cvss_rating/blob/master/lib/cvss_rating/cvss3_vectors.rb#L76

**Comment by mort666** [comment]
So funnily enough I was literally going to look into CVSS 3.1 shortly. 

I need to look through the new spec and see what is different and then I'll update. Will post an update here once I've managed to take a look and have a proper ETA.

**Comment by AgoraSecurity** [comment]
Great. I did some research and it's mainly just adding (or removing) information in order to make analysts work easier when assigning a CVSSv3.

"Changes between CVSS versions 3.0 and 3.1 focus on clarifying and improving the existing standard without introducing new metrics or metric values, and without making major changes to existing formulas. The significant changes are explained below." Source:
https://www.first.org/cvss/v3.1/user-guide

I think the part "without introducing new metrics or metric values, and without making major changes to existing formulas." makes this change easier :)

**Comment by mort666** [comment]
I did just take a quick look at that, there do seem to be some changes to how the calculations are done with some rounding changes and it seems a change to the ModifiedImpact sub-formula. I'll have a proper read though and see what is truly different..
